<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="LocalHelper.fs" />
		<Compile Include="puzzle01\Puzzle01.fs" />
		<Compile Include="puzzle02\Puzzle02.fs" />
		<Compile Include="puzzle03\Puzzle03.fs" />
		<Compile Include="puzzle04\Puzzle04.fs" />
		<Compile Include="puzzle05\Puzzle05.fs" />
		<Compile Include="puzzle06\Puzzle06.fs" />
		<Compile Include="puzzle07\Puzzle07.fs" />
		<Compile Include="puzzle08\Puzzle08.fs" />
		<Compile Include="puzzle09\Puzzle09.fs" />
		<Compile Include="puzzle10\Puzzle10.fs" />
		<Compile Include="puzzle11\Puzzle11.fs" />
		<Compile Include="puzzle12\Puzzle12.fs" />
		
		<Content Include="puzzle01\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle01\puzzle01_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle02\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>		
		<Content Include="puzzle02\puzzle02_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle03\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle03\puzzle03_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle04\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle04\puzzle04_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle05\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle05\puzzle05_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle06\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle06\puzzle06_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle07\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle07\puzzle07_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle08\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle08\puzzle08_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle09\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle09\puzzle09_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle10\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle10\puzzle10_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle11\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle11\puzzle11_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<Content Include="puzzle12\input.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="puzzle12\puzzle12_test.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Compile Include="Program.fs" />
	</ItemGroup>

	<ItemGroup />

</Project>
